version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: consolelog_db
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis/redis-stack:latest
    container_name: consolelog_redis
    ports:
      - '${REDIS_PORT}:6379'
    command: ['redis-server', '--requirepass', 'consolelogredis']
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redisdata:/data
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
